// <auto-generated />
using ContactManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManagerApi.Migrations
{
    [DbContext(typeof(ContactDBContext))]
    [Migration("20250123221224_SeedContacts")]
    partial class SeedContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContactManagerApi.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Address = "123 Main St",
                            City = "Los Angeles",
                            Email = "johndoe@example.com",
                            Name = "John Doe",
                            Phone = "1234567890",
                            PostalCode = "90001",
                            State = "CA"
                        },
                        new
                        {
                            Id = 4,
                            Address = "456 Elm St",
                            City = "San Francisco",
                            Email = "janesmith@example.com",
                            Name = "Jane Smith",
                            Phone = "9876543210",
                            PostalCode = "94101",
                            State = "CA"
                        },
                        new
                        {
                            Id = 5,
                            Address = "789 Oak St",
                            City = "Seattle",
                            Email = "alicej@example.com",
                            Name = "Alice Johnson",
                            Phone = "5551234567",
                            PostalCode = "98101",
                            State = "WA"
                        },
                        new
                        {
                            Id = 6,
                            Address = "321 Pine St",
                            City = "Denver",
                            Email = "bobb@example.com",
                            Name = "Bob Brown",
                            Phone = "4445556666",
                            PostalCode = "80201",
                            State = "CO"
                        },
                        new
                        {
                            Id = 7,
                            Address = "654 Cedar Ave",
                            City = "Chicago",
                            Email = "emmad@example.com",
                            Name = "Emma Davis",
                            Phone = "2223334444",
                            PostalCode = "60601",
                            State = "IL"
                        },
                        new
                        {
                            Id = 8,
                            Address = "987 Birch Rd",
                            City = "Austin",
                            Email = "williamw@example.com",
                            Name = "William Wilson",
                            Phone = "1112223333",
                            PostalCode = "73301",
                            State = "TX"
                        },
                        new
                        {
                            Id = 9,
                            Address = "123 Maple Blvd",
                            City = "Miami",
                            Email = "oliviam@example.com",
                            Name = "Olivia Martinez",
                            Phone = "9998887777",
                            PostalCode = "33101",
                            State = "FL"
                        },
                        new
                        {
                            Id = 10,
                            Address = "456 Spruce Ln",
                            City = "Boston",
                            Email = "jamesa@example.com",
                            Name = "James Anderson",
                            Phone = "8887776666",
                            PostalCode = "02101",
                            State = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Address = "789 Willow Dr",
                            City = "Phoenix",
                            Email = "sophiag@example.com",
                            Name = "Sophia Garcia",
                            Phone = "7776665555",
                            PostalCode = "85001",
                            State = "AZ"
                        },
                        new
                        {
                            Id = 12,
                            Address = "321 Aspen Way",
                            City = "Las Vegas",
                            Email = "michaelh@example.com",
                            Name = "Michael Hernandez",
                            Phone = "6665554444",
                            PostalCode = "89101",
                            State = "NV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
